- name: demo on conditions
  hosts: all
  tasks:
    - name: demo on condition[number]
      debug:
        msg: "{{a}}"

    - name: demo on condition strings
      debug:
        msg: {{fruit_name}}