- name: demo on conditions
  hosts: all
  tasks:
    - name: condition strings
      debug:
        msg: "{{fruit_name}}"
      when: fruit_name == "apple"

    - name: condition on number variable
      debug:
        msg: "{{a}}"
      when: (a | int) > 100

    - name: conditions on booleans
      debug:
        msg: {{is_raining}},it's raining
      when: is_raining = true