- name: demo on conditions
  hosts: all
  tasks:
    - name: demo on condition[number]
      debug:
        msg: "{{a}}"
      when: a > 100
    - name: demo on condition strings
      debug:
        msg: "{{fruit_name}}"
      when: "fruit_name == apple"