- name: demo on conditions
  hosts: all
  vars:
    b: 50
    c: false
  tasks:
    - name: condition strings
      debug:
        msg: "{{fruit_name}}"
      when: fruit_name == "apple"

    - name: condition on number variable
      debug:
        msg: "{{a}}"
      when: (a | int) > 100

    - name: conditions on booleans
      debug:
        msg: "{{is_raining}},it's raining"
      when: is_raining | bool

    - name: debug of b
      debug:
        msg: "{{b}}"
      when : b < 100

    - name: debug c
      debug:
        msg: "{{c}},he's liar"
      when: c