- name: Demo on conditions
  hosts: all
  vars:
    fruit_name: apple
  tasks:
    - name: demo on condition of string
      ansible.builtin.debug:
        msg: "{{fruit_name}}"
      when: fruit_name == "apple"