- name: Demo on loops
  hosts: all
  tasks:
    - name: demo on understanding loops
      ansible.builtin.debug:
        msg: The name of the flower is {{ item }}
      loop:
        - Roses
        - Marigold

    - name: Demo on listed map
      ansible.builtin.debug:
        msg: The name and quantity of the fruit {{ item.name }} and {{ item.quantity }}
      loop:
        - { name: "banana" , quantity: 100}
        - { name: "apple" , quantity: 150}

    - name: demo on three list map
      ansible.builtin.debug:
        msg:
          the name is {{ item.name }}the length is  {{ item.length }} and the breadth is {{ item.breadth }}
        loop:
          - { name: "square" , length: 20 , breadth: 30}
          - { name: "rectangle" , length: 30, breadth: 20 }
