- name: Demo on loops
  hosts: all
  tasks:
    - name: demo on understanding loops
      ansible.builtin.debug:
        msg: The name of the flower is {{item}}

      loop:
        - Roses
        - Marigold

    - name: Demo on listed map
      debug:
        msg: The name and quantity of the fruit {{item.quantity}}

      loop:
        - {"bannana",150}
        - {"apple",201}