
- name: demo on parameter testing
  hosts: local
  tasks:
    - name: Create or update key/value pair in AWS SSM parameter store
      community.aws.aws_ssm_parameter_store:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
      loop:
        - {name: "hello" , value: "my name is asritha"}
        - {name: "dev" , value: "devops321"}

