- name: "Declaring a variable at play level"
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Accessing a variable at play level
      ansible.builtin.debug:
        msg: URL == {{URL}}


- name: "DEclaring a variable at task level"
  hosts: all
  tasks:
    - name: Accessing a variable at task level
      ansible.builtin.debug:
        msg: URL == {{URL}}
      vars:
        URL: task.example.com


- name: Declaring a variable in file
  hosts: all
  vars_files:
    - vars.yaml
  tasks:
    - name: Acessing a variable from files
      ansible.builtin.debug:
        msg: URL == {{URL}}




- name: Declaring a variable in inventory file
  hosts: all
  tasks:
    - name: Accessing  a variable from inventory file
      ansible.builtin.debug:
        msg: URL == {{URL}
