- name: "Declaring a variable at play level"
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Accessing a variable at play level
      ansible.builtin.debug:
        msg: URL == {{URL}}

