- name: Declare a variable at play level
  hosts: all
  vars:
    URL: example.play.com

  tasks:
    - name: Calling varaiable at play level
      ansible.builtin.debug:
        msg: URL == {{URL}}





- name: Declare variable at task level
  hosts: all
  tasks:
    - name: Calling varaible at task level
      ansible.builtin.debug:
        msg: URL == {{URL}}

      vars:
        URL: example.task.com





- name: declaring from another file
  hosts: all
  vars_files:
    sample.yml

  tasks:
    - name: accesing variable form another file
      ansible.builtin.debug:
        msg: URL == {{URL}}



