- name: Declare a variable at play level
  hosts: all
  vars:
    URL: example.play.com
  vars_files:
    - sample.yml

  tasks:
    - name: Calling varaiable at play level
      ansible.builtin.debug:
        msg: URL == {{url}}





- name: Declare variable at task level
  hosts: all
  tasks:
    - name: Calling varaible at task level
      ansible.builtin.debug:
        msg: URL == {{URL}}

      vars:
        URL: example.task.com



- name: declaring a variable from other file
  hosts: all
  vars_files:
    - sample.yml

  tasks:
    - name: accessing a varaibale from other file
      ansible.builtin.debug:
        msg: URL == {{URL}}