- name: declaring a varaible at play level
  hosts: all
  vars:
    URL: example.play.com
  tasks:
    - name: accessing a variable at play level
      ansible.builtin.debug:
        msg: URL == {{URL}}


- name: declaring a varaiable at task level
  hosts: all

  tasks:
    - name: accessing a variable at task level
      ansible.builtin.debug:
        msg: URL == {{URL}}

      vars:
        URL: example.task.com


- name : declaring a variable at file level
  hosts: all
  vars_files:
    - var.yml

  tasks:
    - name : accessing  a variable at file level
      ansible.builtin.debug:
        msg: URL == {{URL}}


- name: declaring a variable in inventory file
  hosts: all
  tasks:
    - name: Accesing a varaiable from inventory file
      ansible.builtin.debug:
        msg: URL == {{URL}}



- name: accessing a variable at task level
  hosts: all
  tasks:
    - name: Accesing and declaring a varaiable at task level
      ansible.builtin.debug:
        msg: URL == {{URL}}

      vars:
        URL: "{Hello everyone.com}"




- name: Access a fact
  hosts: all
  tasks:
    - name: Access a fact
      ansible.builtin.debug:
      msg: "ansible-hostname" == {{ansible_fqdn}}