- name: Declare a variable at play level
  hosts: all
  vars:
    URL: example.play.com

  tasks:
    - name: Calling varaiable at play level
      ansible.builtin.debug:
        msg: URL == {{URL}}


- name: Declaring a variable at task level
  hosts: all
  tasks:
    -name: calling a avariable at task level
    ansible.builtin.debug:
       msg: URL == {{URL}}

    vars:
        URL: example.task.com


